title: "{~} wormlogic"
description: Homelab services

theme: dark
color: purple

headerStyle: clean
statusStyle: dot

useEqualHeights: true
target: _blank

disableIndexing: true

fullWidth: true
maxGroupColumns: 6

maxBookmarkGroupColumns: 3

layout:
  Today:
    style: row
    columns: 3
