substitutions:
  device_name: esp-office-01
  friendly_name: Office ESP 01
  area: Office

  api_encryption_key: !secret esp_office_01_api_key
  ota_password: !secret esp_office_01_ota_password

packages:
  common: !include packages/common.yaml
  wifi: !include packages/wifi.yaml
  diagnostics: !include packages/diagnostics.yaml
  bluetooth_proxy: !include packages/bluetooth-proxy.yaml
